### ISSUE TITLE
TODO HW1

### ISSUE THREAD

**Issue by ehud-gordon** [amitir22/ComputerGraphicProcessing#3]
- [ ] Read obj file, populate vertex_positions (MeshModel.cpp)
### Transformations
- [ ] Implement model Transform (default = identity, until add user input), in Scene.cpp
- [ ] Implement LookAt (view transform, default camera: eye(0,0,0), at=(0,0,-1), up=(0,1,0))   in Camera.cpp
- [ ] Compute Projection matrix , - both orth and perspective (Camera.cpp) 
### Rendering
- [ ] Extract x-y values (and z-buffer) (Renderer.cpp)
- [ ] DrawLines (Renderer.cpp)
- [ ] Allow Resizing of window via reshape
### Camera GUI
- [ ] Add New Camera / Delete Camera
- [ ] Select Active Camera
- [ ] Set Camera Projection
- [ ] Move Camera (Translation / zoom / rotation)
- [ ] Choose if the cameras should be rendered as plus sign
### Model GUI
- [ ] Select Active Model (Turn line color to gray)
- [ ] Select Model Frame (Model / World)
- [ ] Move Model
### View GUI
- [ ] Show normals (vertex/face)
- [ ] Add primitive (cube) to models

**Comment by ehud-gordon** [comment]
Broken down to smaller issues
